OPENAI_API_KEY = "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"
GOOGLE_MAPS_API_KEY = "AIzaSyD6CCFkDTM8U7cF-jFXBK0V-qKdGULV468"
SPOONACULAR_API_KEY = "ae07657712384294b2360528ba59afa1"
LINE_CHANNEL_ACCESS_TOKEN = "oHyhRTfQf0b78ThLedxFoYM6aDY2Da0y08bVn1ZubIgKvbOhOJhFf4VGDV3Gu/yFra2mzr7ewBkxNFALOEg6PQ44mYgxusDel8bw8jD4AFhN2LGbfVurBFlBSUdRA63WjYed2xHC52+8AaqMtpR4ZgdB04t89/1O/w1cDnyilFU="
LINE_TARGET_USER_ID = "U58b6f171a3f1c3067a5d0a335658abed"